SKILLS = [
    "Agentic AI",
    "RAG Systems",
    "Multi-Agent Systems",
    "LLM-as-a-Judge Scoring",
    "Golden Datasets",
    "Persistent Memory",
    "Model Routing & Fallbacks",
    "Supervised & Unsupervised Machine Learning",
    "Text Analytics & NLP",
    "User Clustering",
    "Price Elasticity Modeling",
    "Time Series Forecasting",
    "Model Validation",
    "Model Governance & Version Control",
    "LangGraph",
    "LangChain",
    "LlamaIndex",
    "LiteLLM",
    "Exa Web Search",
    "Langfuse Tracing",
    "Ollama",
    "GPT Models",
    "Claude",
    "Gemini",
    "MongoDB Atlas Vector Search",
    "Pinecone",
    "AWS",
    "AWS Bedrock",
    "AWS ECR/ECS",
    "AWS EC2",
    "GCP",
    "Snowflake",
    "Databricks",
    "PySpark",
    "Python",
    "FastAPI",
    "Streamlit",
    "SQL",
    "Bubble",
    "Pandas",
    "Numpy",
    "Matplotlib",
    "Seaborn",
    "Scikit-learn",
    "Keras",
    "Beautiful Soup",
    "Web Scraping",
    "Git",
    "WordPress",
    "MS Excel",
    "Tableau",
    "Microservice Architecture",
    "CI/CD Pipelines",
    "GitHub Actions",
    "Docker",
    "Data-Modeling"
]
ALIASES = {
    "multi-agent": "multi-agent systems",
    "multi agent systems": "multi-agent systems",
    "multi-agent workflows": "multi-agent systems",
    "multiple agents": "multi-agent systems",
    "agent orchestration": "multi-agent systems",
}